server:
  port: 8081

spring:
  application:
    name: customer-service-bank
  data:
    mongodb:
      uri: mongodb://localhost:27018/MsBank
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html