server:
  port: 8081

spring:
  application:
    name: customer-service-bank
  data:
    mongodb:
      uri: mongodb://localhost:27018/MsBank
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka