server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/MsFixedTerm
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka