server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        enabled: true
        locator:
          enabled: true
      routes:
        - id: customer-service-bank
          uri: lb://customer-service-bank
          predicates:
            - Path=/api/customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: customer
                statusCodes: 500 
            - StripPrefix=2
            - RewritePath=/api/customer/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"