server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        enabled: true
        locator:
          enabled: true
      routes:
        - id: customer-service-bank
          uri: lb://customer-service-bank
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
            - RewritePath=/api/customer/(?<segment>.*), /$\{segment}
        - id: fixedterm-service-bank
          uri: lb://fixedterm-service-bank
          predicates:
            - Path=/api/fixedterm/**
          filters:
            - StripPrefix=2
            - RewritePath=/api/fixedterm/(?<segment>.*), /$\{segment}
        - id: current-service-bank
          uri: lb://current-service-bank
          predicates:
            - Path=/api/current/**
          filters:
            - StripPrefix=2
            - RewritePath=/api/current/(?<segment>.*), /$\{segment}
        - id: saving-service-bank
          uri: lb://saving-service-bank
          predicates:
            - Path=/api/saving/**
          filters:
            - StripPrefix=2
            - RewritePath=/api/saving/(?<segment>.*), /$\{segment}

# resilience4j:
#   circuitbreaker:
#     configs:
#       defecto:
#         sliding-window-size: 10
#         failure-rate-threshold: 50
#         wait-duration-in-open-state: 20s
#         permitted-number-of-calls-in-half-open-state: 5
#         slow-call-rate-threshold: 50
#         slow-call-duration-threshold: 2s
#     instances:
#       customer:
#         base-config: defecto
#       fixedterm:
#         base-config: defecto
#   timelimiter:
#     configs:
#       defecto:
#         timeout-duration: 2s
#     instances:
#       customer:
#         base-config: defecto
#       fixedterm:
#         base-config: defecto

management:
  endpoints:
    web:
      exposure:
        include: "*"