server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/MsSaving
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost